name: Cypress Tests using Cypress Docker Image

on:
  push:
    branches: [master]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Cypress Run
        uses: cypress-io/github-action@v2.9.7
        with:
          start: npm run serve
          wait-on: http://localhost:8080/
          config_file: cypress.json
          spec: "tests/e2e/**/*"
       
