name: E2E Tests (Cypress)

on:
  push:
    branches: [master]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node.js environment
        uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Cypress Run
        uses: cypress-io/github-action@v2.9.7
        with:
          start: npm run serve
          wait-on: http://localhost:8080/
          config_file: cypress.json
          spec: "tests/e2e/**/*"
          record: true
          env: lastName=B
        env:
          CYPRESS_firstName: Benni
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
       
