name: CI & CD Pipeline
on:
  push:
    branches: [master]

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node.js environment
        uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Installing project dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm run test:unit
      - name: Building Dist
        run: npm run build
      - name: Deploy App To Digital Ocean (via scp)
        uses: appleboy/scp-action@master
        env:
          HOST: ${{secrets.SSH_HOST}}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          KEY: ${{secrets.SSH_KEY}}
          PASSPHRASE: ${{ secrets.SSH_PASSWORD }}
        with:
          source: "/home/runner/work/Schach_Vue/Schach_Vue/dist/"
          target: "/var/www/schach-vue/html"
